services:

  gokapi:
    image: sudohash/gokapi:latest
    container_name: gokapi-server
    restart: always
    ports:
      - "53842:53842"
    environment:
      TZ: Asia/Kolkata
      GOKAPI_LENGTH_ID: 15
      GOKAPI_LENGTH_HOTLINK_ID: 40
      GOKAPI_CONFIG_DIR: config
      GOKAPI_CONFIG_FILE: config.json
      GOKAPI_DATA_DIR: data
      GOKAPI_CHUNK_SIZE_MB: 45
      GOKAPI_MAX_FILESIZE: 102400
      GOKAPI_MAX_MEMORY_UPLOAD: 50
      GOKAPI_MAX_PARALLEL_UPLOADS: 4
      TMPDIR: /app/data/tmp
      GOKAPI_DISABLE_CORS_CHECK: false
      GOKAPI_LOG_STDOUT: false
      GOKAPI_ENABLE_HOTLINK_VIDEOS: false
      DOCKER_NONROOT: false
    volumes:
      - data:/app/data
      - config:/app/config

volumes:
  data:
  config:
