name: Docker Publish Latest Multiarch

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: install buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest
      
      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_PW}}
      
      - name: build the image
        run: |
          docker buildx build --tag sudohash/gokapi:latest --platform linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64 .
      
      - name: push the image
        run: |
          docker buildx build --push --tag sudohash/gokapi:latest --platform linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64 .
